name: jan_saarthi
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_localizations:
    sdk: flutter
  speech_to_text: ^6.7.0
  flutter_tts: ^4.0.2
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  url_launcher: ^6.3.1
  provider: ^6.1.2
  razorpay_flutter: ^1.3.5
  pdf: ^3.11.1
  printing: ^5.13.4
  open_file: ^3.5.9
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  firebase_database: ^11.1.6
  timeline_tile: ^2.0.0
  fluttertoast: ^8.2.12
  firebase_storage: ^12.3.4
  mailer: ^6.1.1
  firebase_messaging: ^15.1.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/jan.png
